### ISSUE TITLE
[EPIC] 

### ISSUE THREAD

**Issue by nandordudas** [nandordudas/rtmpg#1]
### Component

auth

### Priority

critical

### Epic Description

dfsg

### Business Value

dfg

### Objectives

- [ ] Objective 1
- [ ] Objective 2
- [ ] Objective 3

### Technical Requirements

dg

### Stories

- [ ] Story 1 (#issue-number)
- [ ] Story 2 (#issue-number)

### Definition of Done

- [ ] All stories completed
- [ ] All tests passing
- [ ] Documentation updated
- [ ] Performance metrics met
- [ ] Code reviewed and merged

### Start Date

dfg

### Target Completion Date

dfg
