### ISSUE TITLE
[EPIC]

### ISSUE THREAD

**Issue by nandordudas** [nandordudas/rtmpg#2]
### Epic Description

A clear and concise description of what this epic encompasses

### Business Value

Describe the business value this epic delivers

### Objectives

- [ ] Objective 1
- [ ] Objective 2
- [ ] Objective 3

### Technical Requirements

List the technical requirements for this epic

### Component

auth

### Status

Backlog

### Priority Level

P0

### Size

XS

### Estimate (story points)

1

### Iteration

Current iteration

### Definition of Done

- [ ] All stories completed
- [ ] All tests passing
- [ ] Documentation updated
- [ ] Performance metrics met
- [ ] Code reviewed and merged
